language: ruby
gemfile:
   - test/support/Gemfile
rvm:
  - 1.9.2
  - 1.9.3
script:
  - bundle exec rake knife
  - bundle exec rake foodcritic
branches:
  only:
    - master
matrix:
  include:
  - rvm: 1.9.2
    gemfile: test/support/Gemfile.1.9.2
  exclude:
  - rvm: 1.9.2
    gemfile: test/support/Gemfile